version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    volumes:
      - ./.env:/var/www/html/.env
      - ./storage:/var/www/html/storage
    depends_on:
      - db
    networks:
      - orkido-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: orkido
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - orkido-network

volumes:
  mysql_data:

networks:
  orkido-network:
    driver: bridge
