<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="preconnect" href="https://fonts.bunny.net">
        <link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet" />
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

        <!-- Scripts -->
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body class="font-sans text-gray-900 antialiased overflow-hidden">
        <!-- Animated Floating Bubbles Background -->
        <div class="fixed inset-0 overflow-hidden pointer-events-none">
            <div class="bubble-container">
                <!-- Bubbles will be generated by JavaScript -->
            </div>
        </div>
        
        <div class="min-h-screen flex flex-col items-center justify-center relative z-10">
            {{ $slot }}
        </div>

        <style>
            body {
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                min-height: 100vh;
                font-feature-settings: "liga" 1, "kern" 1;
                -webkit-font-smoothing: antialiased;
                -moz-osx-font-smoothing: grayscale;
            }

            /* Ensure fonts are loaded */
            .font-display {
                font-display: swap;
            }

            /* Better text rendering for headings */
            h1 {
                text-rendering: optimizeLegibility;
                -webkit-font-smoothing: antialiased;
                -moz-osx-font-smoothing: grayscale;
            }

            .bubble-container {
                position: absolute;
                width: 100%;
                height: 100%;
            }

            .bubble {
                position: absolute;
                border-radius: 50%;
                background: linear-gradient(45deg, rgba(255,255,255,0.1), rgba(255,255,255,0.3));
                backdrop-filter: blur(10px);
                border: 1px solid rgba(255,255,255,0.2);
                animation: float 15s infinite linear;
                pointer-events: none;
            }

            .bubble::before {
                content: '';
                position: absolute;
                top: 10%;
                left: 10%;
                width: 50%;
                height: 50%;
                border-radius: 50%;
                background: rgba(255,255,255,0.3);
                filter: blur(5px);
            }

            @keyframes float {
                0% {
                    transform: translateY(100vh) scale(0);
                    opacity: 0;
                }
                5% {
                    opacity: 1;
                }
                90% {
                    opacity: 1;
                }
                100% {
                    transform: translateY(-100vh) scale(1);
                    opacity: 0;
                }
            }

            /* Different bubble colors */
            .bubble.color-1 { background: linear-gradient(45deg, rgba(255,107,107,0.2), rgba(255,107,107,0.4)); }
            .bubble.color-2 { background: linear-gradient(45deg, rgba(72,219,251,0.2), rgba(72,219,251,0.4)); }
            .bubble.color-3 { background: linear-gradient(45deg, rgba(255,204,112,0.2), rgba(255,204,112,0.4)); }
            .bubble.color-4 { background: linear-gradient(45deg, rgba(168,85,247,0.2), rgba(168,85,247,0.4)); }
            .bubble.color-5 { background: linear-gradient(45deg, rgba(34,197,94,0.2), rgba(34,197,94,0.4)); }
            .bubble.color-6 { background: linear-gradient(45deg, rgba(251,146,60,0.2), rgba(251,146,60,0.4)); }
        </style>

        <script>
            // Generate floating bubbles
            function createBubble() {
                const bubble = document.createElement('div');
                bubble.classList.add('bubble');
                
                // Random color
                const colorClass = `color-${Math.floor(Math.random() * 6) + 1}`;
                bubble.classList.add(colorClass);
                
                // Random size
                const size = Math.random() * 60 + 20; // 20px to 80px
                bubble.style.width = size + 'px';
                bubble.style.height = size + 'px';
                
                // Random horizontal position
                bubble.style.left = Math.random() * 100 + '%';
                
                // Random animation duration
                bubble.style.animationDuration = (Math.random() * 10 + 10) + 's';
                
                // Random animation delay
                bubble.style.animationDelay = Math.random() * 5 + 's';
                
                document.querySelector('.bubble-container').appendChild(bubble);
                
                // Remove bubble after animation
                setTimeout(() => {
                    if (bubble.parentNode) {
                        bubble.parentNode.removeChild(bubble);
                    }
                }, 20000);
            }

            // Create bubbles continuously
            setInterval(createBubble, 300);
            
            // Create initial bubbles
            for (let i = 0; i < 15; i++) {
                setTimeout(createBubble, i * 200);
            }
        </script>
    </body>
</html>
